import { config } from 'dotenv';

config();

const {
  PORT,
  DATABASE_HOST,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
  DATABASE_NAME,
  DATABASE_PORT,
  PRIVATE_KEY,
  PUBLIC_KEY,
  NODE_ENV,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_BLOG_POST_BUCKET_NAME,
} = process.env;

export {
  PORT,
  DATABASE_HOST,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
  DATABASE_NAME,
  DATABASE_PORT,
  PRIVATE_KEY,
  PUBLIC_KEY,
  NODE_ENV,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_BLOG_POST_BUCKET_NAME,
};
